POST https://{{host}}/api/graphql
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56
Content-Type: application/json

{
  "operationName": "SaveForLater",
  "variables": {
    "cart": {},
    "item_id": "c0e95895-010d-4b8c-b761-7b71aaeb6946"
  },
  "query": "mutation SaveForLater($cart: InputCart!, $item_id: TargetItemId!) {\n  CreateFromCartSaveForLater(input: {cart: $cart, item_id: $item_id}) {\n    Cart {\n      id\n    }\n    SaveForLater {\n      id\n    }\n  }\n}\n"
}

###

