monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 3
            filename_format: '{date}-{filename}'
            path: '%kernel.logs_dir%/%kernel.environment%.json.log.dev'
            level: debug
        console:
            type:         rotating_file
            path:         "%kernel.logs_dir%/console_%kernel.environment%.json.log.dev"
            level:        debug
            filename_format: '{date}-{filename}'
            max_files:    3
            channels:
                - 'console'
