ecentria-api-skeleton.h.ecentria.com:
    stage: production
    user: ecentria-api-skeleton
    deploy_path: /home/ecentria-api-skeleton
    execute_migrations: true
    forwardAgent: true
    identityFile: /home/bamuser/.ssh/production-web
    symfony_env: prod
    repository: ssh://git@bitbucket.ecentria.tools/svc/ecentria-api-skeleton.git
    sshOptions:
        UserKnownHostsFile: /dev/null
        StrictHostKeyChecking: no