monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels:
                - '!console'
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.json.log'
            level: info
            filename_format: '{date}-{filename}'
            max_files: 10
        console:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.console.json.log'
            level: info
            filename_format: '{date}-{filename}'
            max_files: 10
            channels: 
                - 'console'
