<?php

namespace App\GraphQl\Type\Definition\Output;

use ApiPlatform\Core\GraphQl\Type\Definition\TypeInterface;
use ApiPlatform\Core\GraphQl\Type\TypesContainerInterface;
use App\GraphQl\Type\Definition\Uuid;
use GraphQL\Type\Definition\InterfaceType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

final class CartType extends ObjectType implements TypeInterface
{
    private $typesContainer;
    private $output;

    public function __construct(array $config, bool $output, TypesContainerInterface $typesContainer)
    {
        $config['name'] = ($output ? 'Output' : 'Input') . $this->tryInferName();

        parent::__construct($config);
        $this->typesContainer = $typesContainer;
        $this->output = $output;
    }

    public function getFields(): array
    {
        $this->config['fields'] = [
            'id' => $this->typesContainer->get(($this->output ? 'Output' : 'Input') . 'CartId'),
            'items' => [
                'type' => Type::listOf($this->typesContainer->get(($this->output ? 'Output' : 'Input') . 'CartItem'))
            ]
        ];
        return parent::getFields(); // TODO: Change the autogenerated stub
    }

    public function getName(): string
    {
        return $this->name;
    }

    public static function create($output = false)
    {
        return new self([], $output);
    }
}